"""CATALOGUE.md is generated by the build, and these tests hold the generator.

The page used to be committed, with a test that failed when the copy and the
generator disagreed. That kept it current, and it made the page the second most
conflicted file in the repository: its component total and its per-part device
counts moved with nearly every pull request, so any two open pull requests
conflicted on it and the second to merge had to merge main in and regenerate.
It is gitignored now, and `./build.sh` writes it on every build.

WHAT IS LEFT TO TEST IS THE GENERATOR AND ITS WIRING. A stale page can no
longer be committed, but a generator that silently drops parts writes one fresh
and wrong, and a build that stops writing it leaves every checkout with the page
it last had. A stale generated page is worse than no page: it carries the same
air of authority either way, and the whole point of it is that somebody searches
it before drawing a part they already have.
"""
import pathlib
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
LIB = ROOT / "library"

from portrayal import components_catalogue as cat


@pytest.fixture(scope="module")
def generated():
    return cat.build(LIB)


def test_the_page_is_gitignored_and_the_build_writes_it():
    """THE WIRING, read as text: running the build here would cost a build.
    Without the ignore line a build leaves the page in `git status` and it gets
    committed again; without the build step nothing keeps it current."""
    ignored = (LIB / ".gitignore").read_text().splitlines()
    assert "components/CATALOGUE.md" in ignored
    script = (ROOT / "build.sh").read_text()
    assert "components_catalogue.py" in script
    assert "--out library/components/CATALOGUE.md" in script


def test_out_writes_the_page_build_returns(tmp_path):
    """`--out` is how build.sh writes the page, and the file must be the page
    whole. A one-part library, so the expected row can be stated exactly."""
    contract = tmp_path / "components" / "std" / "x" / "v1"
    contract.mkdir(parents=True)
    (contract / "contract.yaml").write_text(
        "format: 1\nkind: component\nname: x\nversion: 1.0.0\n"
        "class: port\nsize: {w: 2, h: 3}\ndescription: A test part. More.\n")
    (tmp_path / "devices").mkdir()
    out = tmp_path / "CATALOGUE.md"
    assert cat.main(["--library", str(tmp_path), "--out", str(out)]) == 0
    page = out.read_text(encoding="utf-8")
    assert page == cat.build(tmp_path)
    assert "| `std/x@1` | component | port | 2 × 3 |  | 0 | 0 | A test part |" in page
    assert "\n1 component majors in " in page


def test_every_component_major_in_the_library_has_a_row(generated):
    """Every major on disk has a row, and the page's own summary line gives
    the real count.

    The non-vacuity guard as well: a page generated from a library the walker
    failed to find is short rather than wrong-looking. If the glob ever stops
    matching, this fails rather than passing quietly.
    """
    on_disk = {f"`{c.parts[-4]}/{c.parts[-3]}@{c.parts[-2][1:]}`"
               for c in LIB.glob("components/*/*/v*/contract.yaml")}
    assert len(on_disk) > 400, f"only {len(on_disk)} contracts found - the walk is broken"
    missing = sorted(ref for ref in on_disk if ref not in generated)
    assert not missing, f"{len(missing)} component(s) have no row, e.g. {missing[:5]}"
    assert f"{len(on_disk)} component majors" in generated


def test_the_page_tells_the_reader_how_to_regenerate_it(generated):
    """A generated file that does not say it is generated gets hand-edited, and
    the edit is lost the next time somebody runs the generator."""
    assert "components_catalogue.py" in generated.split("\n\n")[1]


def test_a_superseded_by_pointer_does_not_count_as_a_use(tmp_path):
    """`superseded-by:` names a successor without composing it - the same
    shape as `unplaced:` naming the part that replaced it, and the same reason
    neither should read as a use. Without `without_non_use_refs` stripping it
    too, a retired part's `superseded-by` line inflates its successor's
    `in parts` count exactly the way `common/sfp-lc-duplex@1`'s did the day
    this field landed: 1 became 2, 3 became 4, for a part that composes
    nothing new. This builds a throwaway two-component library instead of
    relying on the real one staying shaped this way."""
    successor = tmp_path / "components" / "generic" / "sfp-lc" / "v1"
    successor.mkdir(parents=True)
    (successor / "contract.yaml").write_text(
        "format: 1\nkind: component\nname: sfp-lc\nversion: 1.0.0\n"
        "class: transceiver\nsize: {w: 1, h: 1}\n")
    retired = tmp_path / "components" / "common" / "sfp-lc-duplex" / "v1"
    retired.mkdir(parents=True)
    (retired / "contract.yaml").write_text(
        "format: 1\nkind: component\nname: sfp-lc-duplex\nversion: 1.0.0\n"
        "class: transceiver\nsize: {w: 1, h: 1}\n"
        "unplaced: superseded by generic/sfp-lc@1, which replaces it entirely\n"
        "superseded-by: generic/sfp-lc@1\n")
    composed = cat.composed_by(tmp_path)
    assert composed.get("generic/sfp-lc@1", set()) == set(), composed.get("generic/sfp-lc@1")


def test_a_device_that_only_names_a_part_in_prose_does_not_seat_it():
    """#348: the `devices` column counted a ref anywhere in a manifest's text,
    so a device explaining why it does NOT use a part counted as seating it.
    common/usb-a-bezel@1 was "seated by 9"; four of those only name it in
    provenance - three of them to say a bare std/usb-a fits where it does not."""
    seats = cat.seated_by(LIB)["common/usb-a-bezel@1"]
    for prose_only in ("ufispace/s9500-30xs", "ufispace/s9510-30xc",
                       "ufispace/s9705-48d", "maiaedge/pbc-2000"):
        assert prose_only not in seats, prose_only
    for placed in ("ufispace/s9510-28dc", "ufispace/s9600-64x"):
        assert placed in seats, placed


def test_a_part_a_bay_only_accepts_is_still_seated():
    """Accepting a part is a seat the configuration can fill, so a card no
    configuration puts in still counts for every chassis whose bay accepts it -
    the count is structural, not a census of shipped builds."""
    seats = cat.seated_by(LIB)
    assert "cisco/asr-9006" in seats["cisco/a9k-rsp880-se@2"]
