"""CATALOGUE.md is generated, and the page says so in its own first paragraph.

    Generated by `python3 spec/tools/portrayal/components_catalogue.py --library library`;
    a test fails when this page and the library disagree.

That sentence is a promise the repository makes to a reader, and it is only true
if this file exists. Without it the page goes stale exactly the way it already
did - the draft was written when the library held 558 components in 10
namespaces and by the time it was picked up it held 587 in 11, with no sign on
the page that anything had moved.

A STALE GENERATED PAGE IS WORSE THAN NO PAGE. A reader has no way to tell; it
carries the same air of authority either way, and the whole point of it is that
somebody searches it before drawing a part they already have.
"""
import pathlib
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
LIB = ROOT / "library"
PAGE = LIB / "components" / "CATALOGUE.md"

from portrayal import components_catalogue as cat


@pytest.fixture(scope="module")
def generated():
    return cat.build(LIB)


def test_the_committed_page_is_what_the_generator_produces(generated):
    """THE PROMISE THE PAGE MAKES, checked.

    Regenerated in-process rather than through a subprocess: the comparison is
    the point, and shelling out would add a second interpreter start to the
    suite for nothing.
    """
    committed = PAGE.read_text()
    if committed == generated:
        return
    # a diff, not "they differ" - the fix is one command and the reader should
    # be able to see whether it is drift or a change they did not expect
    import difflib
    diff = "\n".join(list(difflib.unified_diff(
        committed.splitlines(), generated.splitlines(),
        "committed CATALOGUE.md", "generated", lineterm=""))[:40])
    pytest.fail(
        "library/components/CATALOGUE.md is out of date. Regenerate with:\n"
        "  python3 spec/tools/portrayal/components_catalogue.py --library library "
        "> library/components/CATALOGUE.md\n\n" + diff)


def test_every_component_major_in_the_library_has_a_row(generated):
    """The count in the page's own summary line has to be the real count.

    This is the non-vacuity guard for the test above: two empty strings compare
    equal, and so do two pages generated from a library the walker failed to
    find. If the glob ever stops matching, this fails rather than passing
    quietly.
    """
    on_disk = {f"`{c.parts[-4]}/{c.parts[-3]}@{c.parts[-2][1:]}`"
               for c in LIB.glob("components/*/*/v*/contract.yaml")}
    assert len(on_disk) > 400, f"only {len(on_disk)} contracts found - the walk is broken"
    missing = sorted(ref for ref in on_disk if ref not in generated)
    assert not missing, f"{len(missing)} component(s) have no row, e.g. {missing[:5]}"
    assert f"{len(on_disk)} component majors" in generated


def test_the_page_tells_the_reader_how_to_regenerate_it(generated):
    """A generated file that does not say it is generated gets hand-edited, and
    the edit is lost the next time somebody runs the generator."""
    assert "components_catalogue.py" in generated.split("\n\n")[1]


def test_a_superseded_by_pointer_does_not_count_as_a_use(tmp_path):
    """`superseded-by:` names a successor without composing it - the same
    shape as `unplaced:` naming the part that replaced it, and the same reason
    neither should read as a use. Without `without_non_use_refs` stripping it
    too, a retired part's `superseded-by` line inflates its successor's
    `in parts` count exactly the way `common/sfp-lc-duplex@1`'s did the day
    this field landed: 1 became 2, 3 became 4, for a part that composes
    nothing new. This builds a throwaway two-component library instead of
    relying on the real one staying shaped this way."""
    successor = tmp_path / "components" / "generic" / "sfp-lc" / "v1"
    successor.mkdir(parents=True)
    (successor / "contract.yaml").write_text(
        "format: 1\nkind: component\nname: sfp-lc\nversion: 1.0.0\n"
        "class: transceiver\nsize: {w: 1, h: 1}\n")
    retired = tmp_path / "components" / "common" / "sfp-lc-duplex" / "v1"
    retired.mkdir(parents=True)
    (retired / "contract.yaml").write_text(
        "format: 1\nkind: component\nname: sfp-lc-duplex\nversion: 1.0.0\n"
        "class: transceiver\nsize: {w: 1, h: 1}\n"
        "unplaced: superseded by generic/sfp-lc@1, which replaces it entirely\n"
        "superseded-by: generic/sfp-lc@1\n")
    composed = cat.composed_by(tmp_path)
    assert composed.get("generic/sfp-lc@1", set()) == set(), composed.get("generic/sfp-lc@1")


def test_a_device_that_only_names_a_part_in_prose_does_not_seat_it():
    """#348: the `devices` column counted a ref anywhere in a manifest's text,
    so a device explaining why it does NOT use a part counted as seating it.
    common/usb-a-bezel@1 was "seated by 9"; four of those only name it in
    provenance - three of them to say a bare std/usb-a fits where it does not."""
    seats = cat.seated_by(LIB)["common/usb-a-bezel@1"]
    for prose_only in ("ufispace/s9500-30xs", "ufispace/s9510-30xc",
                       "ufispace/s9705-48d", "maiaedge/pbc-2000"):
        assert prose_only not in seats, prose_only
    for placed in ("ufispace/s9510-28dc", "ufispace/s9600-64x"):
        assert placed in seats, placed


def test_a_part_a_bay_only_accepts_is_still_seated():
    """Accepting a part is a seat the configuration can fill, so a card no
    configuration puts in still counts for every chassis whose bay accepts it -
    the count is structural, not a census of shipped builds."""
    seats = cat.seated_by(LIB)
    assert "cisco/asr-9006" in seats["cisco/a9k-rsp880-se@1"]
