#!/usr/bin/env python3
"""What is actually ON a face, per named part, with its visible box and depth.

THE WORK LIST FOR BUILDING A FACE BEFORE PLACING ANYTHING ON IT. For every named
node in a vendor service model: clip its geometry to the panel plane, and if
anything survives inside the face rectangle, report where it lands and how far it
stands proud. One row per component to draw, sorted by depth, which is also the
order they stack.

A GLOBAL DEPTH MAP IS THE WRONG SHAPE OF ANSWER and was tried first. Z-buffering
the whole scene and point-sampling triangle centroids covers about a tenth of the
face, because a large flat panel is one triangle and contributes one pixel;
rasterising half a million triangles properly in Python is slow and still hands
back a picture rather than a list of parts to model.

READ THE ROWS WITH THE POSE IN MIND. `proud` is only as good as how the guide
posed the part: this R740xd model swings the power supply's own handle open, so
that unit reports 39.3 proud against a body that is nothing of the sort. Sizes
survive a pose; depths of moving parts do not. Cross-check anything that moves.

Boxes here are ENVELOPES. Feed a row to cad-outline.py to get the real outline.
"""
import argparse

import json
import pathlib
import re
import struct

import DracoPy
import numpy as np

_a = argparse.ArgumentParser()
_a.add_argument('file')
_a.add_argument('--plane', type=float, required=True,
                help='cut plane in scene z. Geometry behind it is not visible '
                     'and is not reported. Find it with glb-parts.py --zone '
                     'rear, or from a part known to sit in the panel')
_a.add_argument('--face', default='434x86.8', help='chassis WxH in mm')
_a.add_argument('--min-area', type=float, default=25.0,
                help='mm2 of visible box; below this it is a rivet')
_a.add_argument('--top', type=int, default=40)
A = _a.parse_args()
SCENE = pathlib.Path(A.file)
FACE_W, FACE_H = (float(v) for v in A.face.lower().split('x'))
PLANE = A.plane
MIN_AREA = A.min_area


def chunks(path):
    b = pathlib.Path(path).read_bytes()
    off, js, bin_ = 12, None, None
    while off < len(b):
        ln, kind = struct.unpack_from('<II', b, off)
        if kind == 0x4E4F534A:
            js = json.loads(b[off + 8:off + 8 + ln])
        elif kind == 0x004E4942:
            bin_ = b[off + 8:off + 8 + ln]
        off += 8 + ln
    return js, bin_


def mul(a, b):
    return [sum(a[i + k * 4] * b[k + j * 4] for k in range(4))
            for j in range(4) for i in range(4)]


def local(n):
    if 'matrix' in n:
        return list(n['matrix'])
    t = n.get('translation', [0, 0, 0])
    x, y, z, w = n.get('rotation', [0, 0, 0, 1])
    s = n.get('scale', [1, 1, 1])
    return [(1 - 2 * (y * y + z * z)) * s[0], (2 * (x * y + z * w)) * s[0],
            (2 * (x * z - y * w)) * s[0], 0,
            (2 * (x * y - z * w)) * s[1], (1 - 2 * (x * x + z * z)) * s[1],
            (2 * (y * z + x * w)) * s[1], 0,
            (2 * (x * z + y * w)) * s[2], (2 * (y * z - x * w)) * s[2],
            (1 - 2 * (x * x + y * y)) * s[2], 0, t[0], t[1], t[2], 1]


js, sbin = chunks(SCENE)
nodes = js['nodes']
meshdir = SCENE.parent / (SCENE.stem + '-meshes')
lodfile = {}
for mi, mesh in enumerate(js.get('meshes', [])):
    pg = mesh.get('extensions', {}).get('NEEDLE_progressive')
    for lod in (pg or {}).get('lods', []):
        p = meshdir / pathlib.Path(lod.get('path', '')).name
        if p.exists():
            lodfile[mi] = p
            break

cache = {}


def verts(doc, blob, mi, key):
    if key in cache:
        return cache[key]
    P, F, base = [], [], 0
    for prim in doc['meshes'][mi].get('primitives', []):
        dr = prim.get('extensions', {}).get('KHR_draco_mesh_compression')
        if not dr:
            continue
        bv = doc['bufferViews'][dr['bufferView']]
        o = bv.get('byteOffset', 0)
        m = DracoPy.decode(blob[o:o + bv['byteLength']])
        pts = np.asarray(m.points, np.float64)
        P.append(pts)
        F.append(np.asarray(m.faces, np.int64) + base)
        base += len(pts)
    cache[key] = (np.vstack(P), np.vstack(F)) if P else (None, None)
    return cache[key]


rows = {}


def walk(i, m, owner):
    n = nodes[i]
    m = mul(m, local(n))
    nm = n.get('name')
    # A MESH NODE'S OWN NAME IS USUALLY NOT A PART NAME. This exporter calls
    # them Body_7_7.001, Cylinder, Mesh - autogenerated labels that tell a
    # reader nothing. The meaningful name is the nearest ANCESTOR that does not
    # look autogenerated, which is how `DELL_R740XD_ Rear Handle-1.002` gets
    # attached to the geometry that is actually its shell.
    if nm and not re.match(r'^(Body|Cylinder|Mesh|Object|Solid|Part)[\W_\d]',
                           nm):
        owner = nm
    mi = n.get('mesh')
    if mi is not None and owner:
        if mi in lodfile:
            mjs, mbin = chunks(lodfile[mi])
            P, F = verts(mjs, mbin, 0, ('l', str(lodfile[mi])))
        else:
            P, F = verts(js, sbin, mi, ('s', mi))
        if P is not None:
            M = np.array(m, np.float64).reshape(4, 4).T
            v = ((M[:3, :3] @ P.T).T + M[:3, 3]) * 1000.0
            fx = FACE_W / 2 + v[:, 0]
            fy = FACE_H - v[:, 1]
            fz = v[:, 2]
            keep = (fz[F].max(axis=1) > PLANE)
            if keep.any():
                idx = np.unique(F[keep])
                gx, gy, gz = fx[idx], fy[idx], fz[idx]
                inside = ((gx >= -5) & (gx <= FACE_W + 5)
                          & (gy >= -5) & (gy <= FACE_H + 5))
                if inside.any():
                    gx, gy, gz = gx[inside], gy[inside], gz[inside]
                    r = rows.setdefault(owner, [1e9, 1e9, -1e9, -1e9, -1e9])
                    r[0] = min(r[0], gx.min()); r[1] = min(r[1], gy.min())
                    r[2] = max(r[2], gx.max()); r[3] = max(r[3], gy.max())
                    r[4] = max(r[4], gz.max())
    for c in n.get('children', []):
        walk(c, m, owner)


for root in js['scenes'][js.get('scene', 0)]['nodes']:
    walk(root, [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], None)

out = []
for nm, (x0, y0, x1, y1, z1) in rows.items():
    w, h = x1 - x0, y1 - y0
    if w * h < MIN_AREA or w > FACE_W * 0.99:
        continue
    out.append((z1 - PLANE, nm, x0, y0, w, h))
out.sort(reverse=True)

print(f'{len(out)} named parts visible on the rear face '
      f'(cut z {PLANE}, boxes >= {MIN_AREA} mm2, full-width shells dropped)\n')
print(f'{"proud":>7}  {"face x":>7} {"face y":>6} {"w":>7} {"h":>7}   part')
print('-' * 86)
for proud, nm, x0, y0, w, h in out[:A.top]:
    print(f'{proud:7.1f}  {x0:7.2f} {y0:6.2f} {w:7.2f} {h:7.2f}   {nm[:44]}')
