#!/usr/bin/env python3
"""Write library/components/CATALOGUE.md: every component, one row, grouped by
namespace, with what a contributor needs to decide whether to reuse it.

Reads the contracts and the device manifests directly rather than dist/, so the
page can be regenerated and checked without a build. A test fails when the
committed page differs from this script's output.

    python3 spec/tools/portrayal/components_catalogue.py --library library > library/components/CATALOGUE.md
"""
import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REF = re.compile(r"\b([a-z0-9-]+)/([a-z0-9-]+)@(\d+)\b")


def first_sentence(text, limit=110):
    s = " ".join(str(text or "").split())
    s = s.split(". ")[0].rstrip(".")
    return (s[: limit - 1] + "…") if len(s) > limit else s


def size_text(size):
    if not isinstance(size, dict):
        return ""
    w, h, d = size.get("w"), size.get("h"), size.get("d")
    out = f"{w:g} × {h:g}" if w is not None and h is not None else ""
    if d is not None:
        out += f" × {d:g}"
    return out


def composed_by(library):
    """ref -> contracts that compose it through `parts:` (or otherwise name it)."""
    users = defaultdict(set)
    for contract in sorted(library.glob("components/*/*/v*/contract.yaml")):
        own = f"{contract.parts[-4]}/{contract.parts[-3]}@{contract.parts[-2][1:]}"
        for ns, name, major in set(REF.findall(contract.read_text())):
            ref = f"{ns}/{name}@{major}"
            if ref != own:
                users[ref].add(own)
    return users


def seated_by(library):
    """ref -> device slugs whose manifest (or layout) names it, in any key."""
    users = defaultdict(set)
    for dev in sorted(library.glob("devices/*/*/device.yaml")):
        slug = f"{dev.parent.parent.name}/{dev.parent.name}"
        text = dev.read_text()
        for ns, name, major in set(REF.findall(text)):
            users[f"{ns}/{name}@{major}"].add(slug)
        layout = dev.parent / "layout.yaml"
        if layout.exists():
            for ns, name, major in set(REF.findall(layout.read_text())):
                users[f"{ns}/{name}@{major}"].add(slug)
    return users


def build(library):
    library = Path(library)
    users = seated_by(library)
    parts = composed_by(library)
    groups = defaultdict(list)
    for contract in sorted(library.glob("components/*/*/v*/contract.yaml")):
        ns, name, vdir = contract.parts[-4], contract.parts[-3], contract.parts[-2]
        doc = yaml.safe_load(contract.read_text()) or {}
        ref = f"{ns}/{name}@{vdir[1:]}"
        groups[ns].append({
            "ref": ref,
            "kind": doc.get("kind", ""),
            "class": doc.get("class", ""),
            "size": size_text(doc.get("size")),
            "fits": doc.get("conforms") or doc.get("interface") or doc.get("mates") or "",
            "used": len(users.get(ref, ())),
            "parts": len(parts.get(ref, ())),
            "what": first_sentence(doc.get("description")),
        })
    order = ["std", "common"] + sorted(k for k in groups if k not in ("std", "common"))
    lines = [
        "# Component catalogue",
        "",
        "Generated by `python3 spec/tools/portrayal/components_catalogue.py --library library`;",
        "a test fails when this page and the library disagree. One row per component",
        "major: what it is, how big it is in millimetres (w × h × d), the standard it",
        "conforms to or the interface it presents or mates, how many devices name it and",
        "how many other components compose it. Search this page before drawing a part;",
        "the [components README](README.md) says which namespace a new one belongs in.",
        "",
    ]
    total = 0
    for ns in order:
        rows = groups[ns]
        total += len(rows)
        lines += [f"## {ns}/ ({len(rows)})", "",
                  "| ref | kind | class | size (mm) | conforms / interface | devices | in parts | what it is |",
                  "|---|---|---|---|---|---|---|---|"]
        for r in rows:
            lines.append(f"| `{r['ref']}` | {r['kind']} | {r['class']} | {r['size']} | {r['fits']} | {r['used']} | {r['parts']} | {r['what']} |")
        lines.append("")
    lines[9:9] = [f"{total} component majors in {len(order)} namespaces.", ""]
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--library", default="library")
    args = ap.parse_args(argv)
    sys.stdout.write(build(args.library))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
